dist: trusty
language: c
sudo: true

cache:
    apt: true

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
      - python3
      - python-virtualenv

before_install:
  - git clone https://github.com/rdaly525/coreir.git
  - export COREIRCONFIG="g++-4.9";
  - virtualenv --python=python3 env
  - source env/bin/activate
  - pip install -r requirements.txt  
  - cd coreir
  - make -j
  - sudo make -j install
  - cd -
  - pip install coreir
  - make -j

script:
  - make test
  - make pytest

compiler:
  - gcc

os:
  - linux
