dist: trusty
language: c
sudo: true

cache:
    apt: true

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
      - python3
      - python-virtualenv

before_install:
  - git clone -b dev https://github.com/rdaly525/coreir.git
  - export COREIRCONFIG="g++-4.9";
  - export COREIR=`pwd`/coreir
  - export LD_LIBRARY_PATH=`pwd`/coreir/lib:$LD_LIBRARY_PATH
  - virtualenv --python=python3 env
  - source env/bin/activate
  - pip install pytest  
  - cd coreir
  - make -j2 all
  - sudo make -j2 install
  - cd -
  - pip install coreir
  - make -j2 all

script:
  - make test
  - make pytest

compiler:
  - gcc

os:
  - linux
