dist: trusty
language: c
sudo: true

cache:
    apt: true

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
      - g++-4.9

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - source .travis/install_coreir.sh
  - make -j

script:
  - make test
  - make pytest

compiler:
  - gcc

os:
  - linux
